### ISSUE TITLE
Better design on Example app

### ISSUE THREAD

**Issue by lfarah** [nferocious76/AutoCompleteTextField#13]
I did this quick mockup in Sketch. If you approve it I can implement it and send a pull request 😉 
<img width="371" alt="screen shot 2016-07-17 at 7 05 08 pm" src="https://cloud.githubusercontent.com/assets/6511079/16903313/6d0adc1c-4c51-11e6-9298-f9a298fb5ee0.png">

**Comment by nfhipona** [comment]
haha yes this is cool! please do. thanks! 

: if you think of it, my example was just so done by a kiddo! 😂
