### ISSUE TITLE
autoCompleteTextField. emailDomain

### ISSUE THREAD

**Issue by lfarah** [nferocious76/AutoCompleteTextField#14]
I believe that most people will use **AutoCompleteTextField** as an autocomplete for emails, so instead of having them copy and paste that huge **domainNames** array, we could have something like that:

``` swift
public func autoCompleteTextFieldDataSource(autoCompleteTextField: AutoCompleteTextField) -> [String] {

        return autoCompleteTextField.emailDomain
}
```

**Comment by nfhipona** [comment]
ahh good idea! I will make a default supported domains and they could just use the datasource to let their own supported domains kick in. 👌

**Comment by lfarah** [comment]
Maybe something like this?

``` swift
let myTextField = AutoCompleteTextField(frame: CGRectMake(0, 0, 100, 30))
myTextField.type = .email
```

**Comment by nfhipona** [comment]
ohhh that could also be an option for email or name collections. but I don't think we should support names since it was so huge of a collection. if they want this to get hooked, they can use the datasource to load their own collection.

**Comment by lfarah** [comment]
Definitely! 👍

**Comment by nfhipona** [comment]
Added default supported domains.

**Comment by lfarah** [comment]
Now we have to update the `Readme.md`

**Comment by nfhipona** [comment]
Okay thanks for the note.

**Comment by nfhipona** [comment]
Updated
