### ISSUE TITLE
autoCompleteTextFieldDataSource string starting with Capital letter bug

### ISSUE THREAD

**Issue by lfarah** [nferocious76/AutoCompleteTextField#17]
AutoCompleteTextField won't autocomplete if a string has it's initial character Capital.
Array tested:
`["São Paulo", "Salvador", "Macapa", "Salvador do Sul"]`
Tried to use `ignoreCase = true`, but it didn't work

**Comment by nfhipona** [comment]
Added Fix

**Comment by lfarah** [comment]
thanks!
