### ISSUE TITLE
Unable to find a specification for `AutoCompleteTextField`

### ISSUE THREAD

**Issue by shshalom** [nferocious76/AutoCompleteTextField#19]

**Comment by lfarah** [comment]
@shshalom can you explain more?

**Comment by shshalom** [comment]
Sure,
if I provide my PodFile with the following line:

``` ruby
 pod 'AutoCompleteTextField'
```

and then pod install or update it throws me an error saying:

> Unable to find a specification for `AutoCompleteTextField`

It does work if I add the git argument with AutoCompleteTextField repo url, like so:

``` ruby
pod "AutoCompleteTextField", :git => 'https://github.com/nferocious76/AutoCompleteTextField.git'`
```

**Comment by nfhipona** [comment]
I'll add a fix for this issue later.. thanks. Please use that 'force find' at the moment.

**Comment by nfhipona** [comment]
Updated. You should be able to install it without doing a force find.

**Comment by shshalom** [comment]
Thanks!
