### ISSUE TITLE
Update to Swift 2.2

### ISSUE THREAD

**Issue by lfarah** [nferocious76/AutoCompleteTextField#2]

**Comment by nfhipona** [comment]
Talk about update! 👍  I have forgotten to update this pod 🍡  and its almost Swift 3.0!

**Comment by lfarah** [comment]
@nferocious76 we can create a swift3 branch and I can update it. Then when **Xcode 8 GM** comes up we can merge with master

**Comment by nfhipona** [comment]
Ah yes.. no problem! thanks. I have never visited this project since I thought no one would use it. I think I need to visit this one from time to time haha
