### ISSUE TITLE
Extra steps needed to get AutoCompleteTextField working

### ISSUE THREAD

**Issue by lfarah** [nferocious76/AutoCompleteTextField#3]
`myTextField.autoCompleteTextFieldDataSource = self` didn't work for me. I had to set `myTextField.dataSource = self` to make it work.

**Comment by nfhipona** [comment]
I have recheck this 'autoCompleteTextFieldDataSource' and it is working. How am I able to replicate this one? thanks

**Comment by nfhipona** [comment]
I will update this tomorrow and I will lock 'dataSource'. And it should only be accessible from the IB.

**Comment by lfarah** [comment]
[LFLoginController](https://github.com/awesome-labs/LFLoginController) is using it. Search for `txtEmail.autoCompleteTextFieldDataSource` on `LFLoginController.swift`

**Comment by nfhipona** [comment]
okay let me clone

**Comment by nfhipona** [comment]
@lfarah I have checked this and it was working great. You're just maybe confused because there is a 'setDelimiter("@")' so that means it will only suggest like : 'gmail' after '@' like @'gmail.com'. :)
