### ISSUE TITLE
Return button doesn't work on Example app

### ISSUE THREAD

**Issue by lfarah** [nferocious76/AutoCompleteTextField#4]
In order to autocomplete a textfield, the user has to press the _Return_ button. The problem is that the return button isn't working in the Simulator right now. The only way it works is by pressing <kbd>tab</kbd>.

**Comment by nfhipona** [comment]
Yes. This is not supported yet (I have issues with the default 'delegate' of the TextField that will point on the controller where it was attached and then it was left behind). I'll support this on the next update. Thanks for pointing out.

**Comment by nfhipona** [comment]
@lfarah code is updated. :) if 'delegate' is not set, return should work fine (should dismiss). But if is set, you need to handle this in your delegate controller. Also please use this one 'autoCompleteTextFieldDelegate' when settings the delegate for just conformity either way 'delegate=' should work the same.
