### ISSUE TITLE
Manual Installation

### ISSUE THREAD

**Issue by lfarah** [nferocious76/AutoCompleteTextField#6]
`CocoaPods` is an awesome tool and make our life really easier, but there are some devs who still don't know how to use them. 

It would be cool to add the _Manual installation_ guide in your `README.md`. You can take a look at my [iOS Readme Template](https://github.com/awesome-labs/iOS-readme-template) to see how you can do it.

**Comment by nfhipona** [comment]
@lfarah Yes! I really have a poor documentation of my projects and that really needs to be reviewed! 😄 👌

**Comment by lfarah** [comment]
I'll take a look at that.
I created this [iOS Open source Readme Template](https://github.com/awesome-labs/iOS-readme-template) to make it easy to have a good Readme

**Comment by nferocious76** [comment]
@lfarah hey, I don't know how 'Carthage' works. So I can't update the instruction. I don't want to put things that I don't know it is working. So if you mind, can you do a pull request again with your carthage settings? thanks.
