### ISSUE TITLE
Swiftlint

### ISSUE THREAD

**Issue by lfarah** [nferocious76/AutoCompleteTextField#7]
I'd be cool to add [Swiftlint](https://github.com/realm/SwiftLint) and it's very easy to install.
I already fixed all the _Swiftlint_ warnings for `AutoCompleteTextField`, so It's all about installing and then I can make a pull request 😄

**Comment by nfhipona** [comment]
@lfarah Swiftlint is only to verify the mistakes of the coder when initializing objects right? I don't think we need this, but let me have some of your thoughts of why we are needing this. Thanks!

**Comment by lfarah** [comment]
Swiftlint helps in following the Swift Guidelines. I fixed about 20 erros in **AutoCompleteTextField**, most of them being in `CGRectMake()`, that has to be `CGRect(x:,y:,:width:,height:)`, `}else{` that had to be `} else {`, `CGRectZero` that had to be `CGRect.zero`.
I always add _Swiftlint_ to all my projects and it's soooo useful. I really love it!

**Comment by nfhipona** [comment]
Ah yes. Those part was actually an Obj-C type initialization. I have issues with compiler before when it was xcode 6.0 it was having too many sourcekit errors. I will keep this in mind thanks! I think let's decide this one later whether  really need it or not. I'll be updating this tomorrow night around this time when I'm in my workstation.  :)

**Comment by nfhipona** [comment]
@lfarah okay updated. All are conforming to swift syntax and there should be no more ObjC syntax traces. 👍
